### ISSUE TITLE
configparser.NoSectionError: No section: 'main'

### ISSUE THREAD

**Issue by siuside** [areed1192/td-ameritrade-api#19]
I cannot get the web page authentication to pop up when I try to run td.client.py in VS Code. There is no error after the python interpreter calls the script, just returns to the terminal. 

Python 3.9.12

```
pi@raspberrypi:~/tos/td-ameritrade-api $ /usr/bin/python /home/pi/tos/td-ameritrade-api/td/client.py
pi@raspberrypi:~/tos/td-ameritrade-api $ 
```

All tests subsequently fail but pasting here in case this puts more context around the errors. 

```
pi@raspberrypi:~/tos/td-ameritrade-api $ /usr/bin/python /home/pi/tos/td-ameritrade-api/tests/test_client.py
EEEEEEEEEEEE
======================================================================
ERROR: test_creates_instance_of_accounts (__main__.TestTdClient)
Create an instance and make sure it's a `Accounts` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_client (__main__.TestTdClient)
Create an instance and make sure it's a `TdAmeritradeClient` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_instruments (__main__.TestTdClient)
Create an instance and make sure it's a `Instruments` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_market_hours (__main__.TestTdClient)
Create an instance and make sure it's a `MarketHours` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_mover (__main__.TestTdClient)
Create an instance and make sure it's a `Movers` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_options_chain (__main__.TestTdClient)
Create an instance and make sure it's a `OptionsChain` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_orders (__main__.TestTdClient)
Create an instance and make sure it's a `Orders` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_price_history (__main__.TestTdClient)
Create an instance and make sure it's a `PriceHistory` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_quote (__main__.TestTdClient)
Create an instance and make sure it's a `Quotes` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_saved_orders (__main__.TestTdClient)
Create an instance and make sure it's a `SavedOrders` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_user_info (__main__.TestTdClient)
Create an instance and make sure it's a `UserInfo` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

======================================================================
ERROR: test_creates_instance_of_watchlists (__main__.TestTdClient)
Create an instance and make sure it's a `Watchlists` object.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/tos/td-ameritrade-api/tests/test_client.py", line 34, in setUp
    client_id = config.get('main', 'client_id')
  File "/usr/local/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.9/configparser.py", line 1152, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

----------------------------------------------------------------------
Ran 12 tests in 0.024s

FAILED (errors=12)
pi@raspberrypi:~/tos/td-ameritrade-api $ 
```

**Comment by BillSchumacher** [comment]
You need to add a config.ini file with a main section like so:
![image](https://user-images.githubusercontent.com/34168009/177046232-6709aa81-3ffd-4128-a2c4-efca596670fc.png)
