### ISSUE TITLE
KeyError: 'code' after I paste the authorization code

### ISSUE THREAD

**Issue by rcholic** [areed1192/td-ameritrade-api#22]
I installed the `td-ameritrade-api` library through `pip install td-ameritrade-api` on my mac.

I used this code as an example to get my access and refresh token: https://github.com/areed1192/td-ameritrade-api/blob/master/samples/use_ouath.py

But when I paste my authorization code in my terminal, 
```
Please Paste the Authorization Code Here: kKMpPxk1GWougVO5Zz7ylBRTGqQhU2sE%2BX5G2rqvaS2UBYBJQz01EZWq6w5%2F2bvo%2BDetIRlW4gG4eQEPVuJCnjJXUQMRqYFPLttct01SwVRRADOW1VX2MzRWPZ5WxF4%2FNjoH3C5CAHR7fnA%2F21hJH%2F5IZvotgDUKFX8hLQPpMJ8brksP%2FijXPuKksDHKmA2KlkvpqXXj3TV6Q3aqGQdhi24xU%2FxqrHrcTBR4mABzjgonEVrw5qemE2SKbbi9N1d7RSgiQ2sa7rMVJcJTBuzvgVjx6VSm4w0l4gQU1wruYronOUZWYh4AyMOYqWI16oukGB1aMU0BIb%2FTZHkuPGQCwr1f1QWJ6k01lrIsTP2piz6QRjIeBU3%2FT2YMtaFee8t1zPqxBk%2FDS2%2BCS57XrxZicbFkJswB8wayrUTWLBtWmziQ2nwlKOB8c9OoHjs100MQuG4LYrgoVi%2FJHHvlw7elSTjHMhz4QqYuSfaMSpPhZVYqsKbTdaElOMaPwpgNBMXIH4zsWBhpq%2BXU%2BZMh3l%2BtNhFE%2FWEWUTXvtmjnX1zZNEtDp4ERur9%2FwmtzS0rUYoi2JE6ggmEyXzAlEjx3HuTrr1eHxjiWbQ3kuOegSUla1vblemZCi1oQ9%2BOiQXbwOIw5Or3url77WbZBNFjxpVnbEoShnWtXYQhsFaZJ8lI5zNN1SeUE99a8kQte7MznbTE1X2%2F2EIp8cZ%2FFsa0lhkywT0JKpdljZjqpCmNglzTrvAzDu5GmWQLxnQGTqgfezcmU6WYjIFj2qJ1YbY4431t6zXSIrhm18UO0DlCRjqKdZTbAIfEXwcNCfC0lHgs%2B%2Be4TEqZSlatyiwV10WUOJF53s0mod3oJvC0QgeU2%2FIWNxnr7viG7mPk22xxWLoStdIb5TbXrKCLay0E%3D212FD3x19z9sWBHDJAxxxx

```

I got following error: KeyError: 'code':

```
Traceback (most recent call last):
  File "/Users/user1/test8.py", line 4, in <module>
    tos_client = TOSClient('xxxsfdsfasdfsadfs', '/Users/user1/project/server/toolbox/tos_tokens.json')
  File "/Users/user1/project/server/toolbox/TOSClient.py", line 23, in __init__
    td_credentials = TdCredentials(
  File "/Users/user1/env/lib/python3.9/site-packages/td/credentials.py", line 68, in __init__
    self.from_workflow()
  File "/Users/user1/env/lib/python3.9/site-packages/td/credentials.py", line 361, in from_workflow
    self.grab_authorization_code()
  File "/Users/user1/env/lib/python3.9/site-packages/td/credentials.py", line 475, in grab_authorization_code
    self.authorization_code = parse_code['code'][0]
KeyError: 'code'

```

did anyone see such error? how to fix it? thank you

**Comment by rcholic** [comment]
never mind, solved the problem by pasting the entire url containing the authorization code. thanks
